# action.yml
name: 'Monday App Deploy'
description: 'Deploy app to Monday code'
inputs:
  token:
    description: 'Monday developer token'
    required: true
  appId:
    description: 'The ID of your monday app'
    required: false
  versionId:
    description: 'The version ID of your monday app'
    required: false
  force:
    description: 'Force deploy to live version'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.token }}
  - ${{ inputs.appId }}
  - ${{ inputs.force }}
